for_window [window_type="dialog"] floating enable
for_window [app_id="blueman-manager"] floating enable; swaymsg move position center; swaymsg resize set 60ppt 60ppt

for_window [app_id="org.mozilla.Thunderbird" title="^Write"] floating enable; swaymsg move position center; swaymsg resize set 60ppt 60ppt
for_window [app_id="org.mozilla.Thunderbird" title="^Write"] floating enable; swaymsg move position center; swaymsg resize set 60ppt 60ppt
for_window [app_id="org.gajim.Gajim" title="^Password"] floating enable; swaymsg move position center
