#!/bin/bash

OPTIONS=("poweroff" "reboot" "lock")

SELECTED=$(echo ${OPTIONS[@]} | rofi -sep ' ' -dmenu -p "option")
[[ -z "$SELECTED" ]] && exit

if [ "$SELECTED" = "poweroff" ]; then
    systemctl poweroff
elif [ "$SELECTED" = "reboot" ]; then
    reboot
elif [ "$SELECTED" = "lock" ]; then
    i3lock
fi
