#!/bin/bash

OPTIONS=("poweroff" "reboot" "lock" "logout" "suspend")

SELECTED=$(echo ${OPTIONS[@]} | rofi -sep ' ' -dmenu -p "option")
[[ -z "$SELECTED" ]] && exit

if [ "$SELECTED" = "poweroff" ]; then
    systemctl poweroff
elif [ "$SELECTED" = "reboot" ]; then
    reboot
elif [ "$SELECTED" = "suspend" ]; then
    systemctl suspend
elif [ "$SELECTED" = "logout" ]; then
    loginctl kill-user $USER
elif [ "$SELECTED" = "lock" ]; then
	betterlockscreen -l blur
fi
