#!/bin/bash

_set_bg () {
	feh --no-fehbg --bg-fill $(cat ~/.bgimage)
}

second_display=$(xrandr | grep -Po "(?>[^eDP\-1]).*(?= connected)" | head -n 1)
echo "$second_display"

if [ -z "$second_display" ]; then 
	_set_bg
	return
fi

export DISPLAY=:0
export XAUTHORITY=$HOME/.Xauthority

if grep -q open /proc/acpi/button/lid/LID/state; then
    xrandr --output "$second_display" --primary --right-of eDP-1 --auto
    xrandr --output eDP-1 --auto --noprimary
else
    xrandr --output eDP-1 --off
fi

_set_bg
