[window]
padding = { x = 10, y = 10 }
# decorations = "None"

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
size = 9

[keyboard]  # docs: https://alacritty.org/config-alacritty.html#keyboard
bindings = [
    { key = "i",  mods = "Alt", action = "ToggleViMode" },
    { key = "o", mode = "Vi|~Search", action = "Open" },
]
